FROM python:3.9

WORKDIR app

COPY ./settings.py /app/settings.py
COPY ./redis_parser.py /app/redis_parser.py
COPY ./Usys.py /app/Usys.py
COPY ./requirements.txt /app/requirements.txt
COPY ./logger.py /app/logger.py

RUN apt-get update
RUN MULTIDICT_NO_EXTENSIONS=1 pip3 install multidict
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

# Create logs directory and set permissions
RUN mkdir -p /app/logs && \
    chmod 777 /app/logs

ENV LANG ru_RU.UTF-8
ENV LC_ALL ru_RU.UTF-8

USER 1001

ENTRYPOINT ["python3"]

CMD ["redis_parser.py"]
