FROM python:3.9

WORKDIR app

COPY ./settings.py ./settings.py
COPY ./main.py ./main.py
COPY ./Usys.py ./Usys.py
COPY ./requirements.txt ./requirements.txt

RUN apt-get update
RUN MULTIDICT_NO_EXTENSIONS=1 pip3 install multidict
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

ENV LANG ru_RU.UTF-8
ENV LC_ALL ru_RU.UTF-8

USER 1001

ENTRYPOINT ["python3"]

CMD ["main.py"]
